config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'
  get 'reviews/create'
  resources :dishes
  resources :restaurants
  resources :reviews

  devise_for :users
  get 'home/Index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"  
  root to: "home#Index" 
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/dish.rb
class Dish < ApplicationRecord
  belongs_to :restaurant
  has_many :reviews, as: :reviewable

end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    has_many :dishes
    has_many :reviews, as: :reviewable
    validates :title, presence: true
    validates_associated :dishes
  
    accepts_nested_attributes_for :dishes
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :reviewable, polymorphic: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :restaurants
  has_many :dishes
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :set_dish, only: %i[ show edit update destroy ]

  # GET /dishes or /dishes.json
  def index
    @dishes = Dish.all
  end

  # GET /dishes/1 or /dishes/1.json
  def show
  end

  # GET /dishes/new
  def new
    @dish = Dish.new
  end

  # GET /dishes/1/edit
  def edit
  end

  # POST /dishes or /dishes.json
  def create
    @dish = Dish.new(dish_params)

    respond_to do |format|
      if @dish.save
        format.html { redirect_to dish_url(@dish), notice: "Dish was successfully created." }
        format.json { render :show, status: :created, location: @dish }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dishes/1 or /dishes/1.json
  def update
    respond_to do |format|
      if @dish.update(dish_params)
        format.html { redirect_to dish_url(@dish), notice: "Dish was successfully updated." }
        format.json { render :show, status: :ok, location: @dish }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dishes/1 or /dishes/1.json
  def destroy
    @dish.destroy

    respond_to do |format|
      format.html { redirect_to dishes_url, notice: "Dish was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dish
      @dish = Dish.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dish_params
      params.require(:dish).permit(:title, :name, :price, :restaurants_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def Index
    if params[:search]
      @restaurants = Restaurant.where("name LIKE ?", "%#{params[:search]}%")
    else
      @restaurants = Restaurant.all
    end
  end

  def search
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  #before_action :set_restaurant, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /restaurants or /restaurants.json
  def index
    if params[:dish_name]
      @restaurants = Restaurant.joins(:dishes).where("dishes.name LIKE ?", "%#{params[:dish_name]}%")
    else
    @restaurants = Restaurant.all
    end
  end

  # GET /restaurants/1 or /restaurants/1.json
  def show
    @restaurant = Restaurant.find(params[:id])
    @reviews = @restaurant.reviews
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
    @restaurant.dishes.build
  end

  
  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants or /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to restaurant_url(@restaurant), notice: "Restaurant was successfully created." }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1 or /restaurants/1.json
  def update
    if @restaurant.update(restaurant_params)
      if @restaurant.status_changed?
        RestaurantStatusJob.set(wait: 5.minutes).perform_later(@restaurant.id, @restaurant.status)
      end
      redirect_to @restaurant, notice: "Restaurant was successfully updated."
    else
      render :edit
    end
  end

  # DELETE /restaurants/1 or /restaurants/1.json
  def destroy
    @restaurant.destroy

    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: "Restaurant was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def restaurant_params
      params.require(:restaurant).permit(:title, :status, dishes_attributes: [:name, :price])
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def index
    @reviews = Review.all
  end
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.reviews.new
    # @dish = Dish.find(params[:dish_id])
    # @review = @dish.reviews.build
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    # @dish = Dish.find(params[:dish_id])
    @review = @dish.reviews.build(review_params)
    if @review.save
      redirect_to restaurant_path(@restaurant), notice: 'Review submitted successfully.'
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:rate, :comments, :reviewable_type, :reviewable_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/dishes/_dish.html.erb
<div id="<%= dom_id dish %>">
  <p>
    <strong>Title:</strong>
    <%= dish.title %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= dish.name %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= dish.price %>
  </p>

  <p>
    <strong>Restaurants:</strong>
    <%= dish.restaurants_id %>
  </p>

</div>

app/views/dishes/_form.html.erb
<%= form_with(model: dish) do |form| %>
  <% if dish.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(dish.errors.count, "error") %> prohibited this dish from being saved:</h2>

      <ul>
        <% dish.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :restaurants_id, style: "display: block" %>
    <%= form.text_field :restaurants_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/dishes/edit.html.erb
<h1>Editing dish</h1>

<%= render "form", dish: @dish %>

<br>

<div>
  <%= link_to "Show this dish", @dish %> |
  <%= link_to "Back to dishes", dishes_path %>
</div>

app/views/dishes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Dishes</h1>

<div id="dishes">
  <% @dishes.each do |dish| %>
    <%= render dish %>
    <p>
      <%= link_to "Show this dish", dish %>
    </p>
  <% end %>
</div>

<%= link_to "New dish", new_dish_path %>

app/views/dishes/new.html.erb
<h1>New dish</h1>

<%= render "form", dish: @dish %>

<br>

<div>
  <%= link_to "Back to dishes", dishes_path %>
</div>

app/views/dishes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @dish %>

<div>
  <%= link_to "Edit this dish", edit_dish_path(@dish) %> |
  <%= link_to "Back to dishes", dishes_path %>

  <%= button_to "Destroy this dish", @dish, method: :delete %>
</div>

app/views/home/Index.html.erb
<marquee class="css2" direction="right"><b>Welcome to our Restaurant!!</b></marquee>

<br>
<% if user_signed_in? %> 
 <div> Welcome <%= current_user.email %> </div> 
  <%= button_to "Sign out", destroy_user_session_path, method: :delete %> 
  <center>
    <%= link_to 'Register Your restaurant here!!!', new_restaurant_path %>
  </center>
  <%= link_to 'Registered restaurant list', restaurants_path %>

<% else %>
  <%= button_to "Sign in", new_user_session_path %> 
  <center>
<%= form_with(url: restaurants_path, method: "get") do |f| %>
  <%= f.label :dish_name, "Search Dish:" %>
  <%= f.text_field :dish_name %>
  <%= f.submit "Search" %>
<% end %>
</center>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <p class="notice"><%= notice %></p> 
  <p class="alert"><%= alert %></p> 
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= form_with(model: restaurant) do |form| %>
  <% if restaurant.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
        <% restaurant.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/restaurants/_restaurant.html.erb
<div id="<%= dom_id restaurant %>">
  <p>
    <strong>Title:</strong>
    <%= restaurant.title %>
  </p>

</div>

app/views/restaurants/edit.html.erb
<h1>Editing restaurant</h1>

<div>
  <%= link_to "Show this restaurant", @restaurant %> |
  
</div>
<%= form_for(@restaurant) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :status %>
  <%= f.select :status, ['open', 'closed'] %>

  <%= f.submit %>
<% end %>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>
<%= form_with(url: restaurants_path, method: "get") do |f| %>
  <%= f.label :dish_name, "Search Dish:" %>
  <%= f.text_field :dish_name %>
  <%= f.submit "Search" %>
<% end %>

<table width="500" border="1">
  <thead>
    <tr>
      <th bgcolor="yellow">Restaurant</th>
      <th bgcolor="yellow">status<th>
      <th bgcolor="yellow">Reviews<th>
      <th bgcolor="yellow">Dish</th>
      <th bgcolor="yellow">Price<th>
       
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.title %></td>
        <td><%= restaurant.status %></td>
        <td><%= link_to "Give Review", new_review_path(restaurant_id: restaurant.id) %></td>
        <% if user_signed_in? %> 
        <td>
          <%= link_to "Show", restaurant_path(restaurant), class: "btn btn-primary" %><br>
          <%= link_to "Edit", edit_restaurant_path(restaurant), class: "btn btn-primary" %><br>
          <%= link_to "Delete", restaurant_path(restaurant), method: :delete, data: { confirm: "Are you sure you want to delete?" }, class: "btn btn-danger" %>
        </td>
        <% end %>
        
          <% restaurant.dishes.each do |dish| %>
            <td><%= dish.name %></td><br>
            <td><%= dish.price %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/restaurants/new.html.erb
<center>
<marquee class="css2" direction="right"><b>Register Here !!!!!</b></marquee>
<%= form_for(@restaurant) do |f| %>
  <%= f.label :restaurant_name %>
  <%= f.text_field :title %>
<br>
  <%= f.label :status %>
  <%= f.select :status, options_for_select([['Open', 'open'], ['Closed', 'closed']]), {}, { class: 'form-control' } %>
  <br>

  <%= f.fields_for :dishes do |dish_fields| %>
    <%= dish_fields.label :dish_name %>
    <%= dish_fields.text_field :name %>
<br>
    <%= dish_fields.label :price %>
    <%= dish_fields.text_field :price %>
  <% end %>
<br><br>
  <%= f.submit %>
<% end %>
</center>

app/views/restaurants/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @restaurant %>

<div>
  <%= link_to "Edit this restaurant", edit_restaurant_path(@restaurant) %> |
  <%= link_to "Back to restaurants", restaurants_path %>
  <%= button_to "Destroy this restaurant", @restaurant, method: :delete %>
</div>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<%= form_for @review do |f| %>
 
  
  <%= f.label :rating %>
  <%= f.select :rate, (1..5) %>

   <%= f.label :comments %>
  <%= f.text_area :comments %>
  
  <%= f.hidden_field :reviewable_id, value: @restaurant.id %>
  <%= f.hidden_field :reviewable_type, value: @restaurant.class.to_s %>
  
  <%= f.submit %>
<% end %>